<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Group;
use AppBundle\Entity\User;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserIds($groupId)
    {
        /** @var Group $group */
        $group = $this->find($groupId);

        $users = $group->getUsers();
        $userIds = [];

        /** @var User $user */
        foreach ($users as $user) {
            $userIds[] = $user->getId();
        }

        return $userIds;
    }
}
